### ISSUE TITLE
Can't remove false positive failing check

### ISSUE THREAD

**Issue by nblock** [nijel/weblate#1102]
### Steps to reproduce
1. Add a translation where source and translation are the same
2. This triggers the "unchanged translation" check
3. Click in the "x" to remove the check and hit save
4. The "unchanged translation" check is still there

### Expected behaviour
Clicking on the "x" should remove the check. If I remember correctly, this worked before Weblate 2.6.

### Server configuration
```
 * Weblate 2.6
 * Python 2.7.9
 * Django 1.8
 * six 1.9.0
 * python-social-auth 0.2.7
 * Translate Toolkit 1.14.0-rc1
 * Whoosh 2.7.0
 * Git 2.1.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.4.4
 * django-crispy-forms 1.4.0
 * compressor 1.5
 * djangorestframework 3.3.3
 * pytz 2015.2
 * pyuca N/A
 * pyLibravatar N/A
 * Mercurial 3.3.3
 * Database backends: django.db.backends.postgresql_psycopg2
```

**Comment by nijel** [comment]
It works fine for me, there was no recent change besides adding keyboard shortcuts (this was in 2.5). Maybe your browser has some old cached javascript which causes this? Can you check this with browser developer tools if clicking on the x fires request to the server?

**Comment by nblock** [comment]
I started a new session in private browsing mode and one with an alternative browser and in both of cases no request was fired.

**Comment by nijel** [comment]
As you also see #1103 there must be something broken in the client code for you. Are you using any special browser plugins or antivirus proxy which might modify the page content? Alternatively something might went wrong with server side javascript cache and the served file is incomplete.

**Comment by nijel** [comment]
This is most likely due to generating absolute URLs for many requests and your site URL or HTTPS setting doesn't match it (see https://github.com/nijel/weblate/issues/1107#issuecomment-218726460).

Anyway this was just changed in master, so that absolute URLs will no longer appear in the application (but these settings are still needed for correct URLs in mails or API exports).

Relevant commits:

* 54ebb4b Adjust API to using Django get_absolute_url semantics
* e17706c Revert "Return urls including site in get_absolute_url"
* 4448b63 Revert "Remove get_site_url calls as get_absolute_url now includes site"
* 1eaf8f0 Revert "Adjust tests to new absolute urls"
