### ISSUE TITLE
ability to edit monolingual template file [$50]

### ISSUE THREAD

**Issue by danackerson** [nijel/weblate#405]
would be great to use Weblate as "single source of truth" for all translation activities (and avoid having to give repository access to non-technical colleagues)

**Comment by paulpach** [comment]
This would be helpful for me too.

**Comment by nijel** [comment]
This seems to have quite big demand :-). So let me share my idea how I think it should be implemented, but comments are welcome.

* It can be added to existing source strings view (eg. https://demo.weblate.org/projects/hello/master/source/review/?type=all)
* For monolingual files, it would directly edit the file and update source string of all units
* For bilingual the suggested change should stored as a comment

Related topics:

* The source string review should be probably made more visible on the component page
* There should be edit icon near source string field while translating leading to source string view for this string

Any suggestions how to make this better?

**Comment by paulpach** [comment]
Would be nice to have a zen mode for source string editing (not necessary, just nice).

**Comment by paulpach** [comment]
Another option which might be easier would be to comment out the filtering of the template in subproject:

```python
def get_mask_matches(self):
        '''
        Returns files matching current mask.
        '''
        prefix = os.path.join(self.get_path(), '')
        matches = glob(os.path.join(self.get_path(), self.filemask))
        matches = [f.replace(prefix, '') for f in matches]
        # Template can have possibly same name as translations
        if self.has_template() and self.template in matches:    #comment this out
            matches.remove(self.template)                       #comment this out
        return matches
```

So that the english version (source) becomes just another language in the subproject.  Then editing happens with the regular language editing tools.

What would have to change is that if one edits the template,  then the sources in the corresponding translation units needs to be updated.

Either what you described or this way would work fine for me.

**Comment by nijel** [comment]
@paulpach That's indeed easier option, but I was just not sure if having the source between translations is good idea. However I'm not using monolingual translations much, so I'm probably not the right person to decide this.

Also for some formats (eg. Android), the path for template is different than for translations, but that could be handled as well.

**Comment by nijel** [comment]
Any comments on whether it's better to treat the base translation in a same way and list it among translations or to have it separately somewhere in current source strings review page?

**Comment by FelisCatus** [comment]
I was trying to fix a period warning just a few minutes ago and I found that the period should be added to the source string instead of removing the period in translated strings. It would be nice to be possible to edit the source string directly on Weblate instead of pushing changes to the repo and try again.

I would say listing the source language among translations seems easier to implement and use, while it doesn't make the source language "special" enough. I would also suggest adding a "Source" badge on the list item, and editing a source string should display a hint like "This is the base of all translations. Editing it would update the source string for all other languages".

**Comment by paulpach** [comment]
In my case,  the person editing the source also coordinates with
translators.  This person should be familiar with how translation needs to
be done in weblate.  If he uses the same UI as translators, he might be
able to give them better support.

In addition,  it seems to me that this way you reuse a lot of code, and I
will have the shiny feature sooner rather than later :)

That said, I think both options are quite usable, and he will have no
trouble adapting to either one.

**Comment by paulpach** [comment]
Also, I do believe that if you ad it to the sources page,  I will have to
show him where it is.

If it is just another language,  he will probably be able to figure it out
by himself.

This is not a big deal to me since I will only need to teach him once,  but
since you clearly care about usability, there is that.

**Comment by nijel** [comment]
Okay, I'm on it.

**Comment by nijel** [comment]
The basic implementation is there, it would be great if somebody could test it in real life :-).

**Comment by nijel** [comment]
I believe it now works as intended.

The change will be deployed to Hosted Weblate later, probably after weekend.

**Comment by paulpach** [comment]
Tx nijel,  working on testing it....

**Comment by nijel** [comment]
BTW: Once you update the code, you will have to reload the translations to make this appear, you can do that using ```./manage.py loadpo --all```.

**Comment by paulpach** [comment]
I can confirm it works perfectly.  Thank you!
