### ISSUE TITLE
add robots.txt to exclude bots

### ISSUE THREAD

**Issue by paulpach** [nijel/weblate#679]
It would be great if you added a robots.txt that prevented crawlers from visiting the site.

openshift is very slow as it is,  so the extra load from crawlers is unwanted.  

This is strictly a development tool,  so I don't think anybody would be interested in having it listed in search engines.

**Comment by nijel** [comment]
Actually robots.txt is there, but is quite permissive currently - https://github.com/nijel/weblate/blob/master/weblate/media/robots.txt

I was also thinking about limit as well, but I haven't time to properly tune robots.txt for what I think is reasonable.

IMHO the basic pages should be accessible for search engines, so that user can find it in google. Having indexed translations itself is probably less useful. That basically leads to blacklisting all but pages which are currently listed in the sitemap.xml.

**Comment by paulpach** [comment]
It gives me file not found:

http://weblate-blockstory.rhcloud.com/robots.txt

**Comment by paulpach** [comment]
Hmmm,  I can access it here:

http://weblate-blockstory.rhcloud.com/media/robots.txt

but it needs to be accessible here:

http://weblate-blockstory.rhcloud.com/robots.txt

**Comment by paulpach** [comment]
Tx Nijel,  

but the actual bug is that in openshift,  robots.txt is not accessible at the root level.

**Comment by nijel** [comment]
@paulpach Probably your setup is missing alias for robots.txt as described in http://docs.weblate.org/en/latest/admin/install.html#sample-configuration-for-apache

**Comment by paulpach** [comment]
perhaps the openshift installation scripts should add this?   Because
everyone installing this in openshift will get the same thing.

**Comment by nijel** [comment]
@paulpach Create separate issue for Openshift setup: #709
