### ISSUE TITLE
Import of fuzzy translations

### ISSUE THREAD

**Issue by nijel** [nijel/weblate#751]
On file upload Weblate currently looks only for translated unit. However in many cases it would make sense to import fuzzy translations as well.

This might be specially true for XLIFF, where approved="yes" is frequently missing making all translations fuzzy.

**Comment by Rvanlaak** [comment]
Is there actually an option to 'mark all as approved' on the import? We're migrating from .yml to .xliff and we do not want to mark all items manually.

**Comment by Rvanlaak** [comment]
Saw the commit, seems to solve the 'fuzzy' for us. Our components should always have the exact same number of translations for each language. 

So, if the Dutch file of the `adminbackend` is imported, and the German language does not have the same number of translation keys then they should also be added over there.

We make use of translation keys, instead of a source language. So, for all languages the sources match. Is there a view or search to group the source keys?

**Comment by Rvanlaak** [comment]
And, found the keyboard shortcuts. Maybe add `CTRL + SHIFT + enter` to unmark fuzzy and save.

**Comment by Rvanlaak** [comment]
ping @nijel

**Comment by nijel** [comment]
Can you please make separate issues for these things? Adding more and more stuff to existing issue really does not help. As for using translation keys, you should use monolingual base file to define source strings (it also defines translation keys to be used) see https://docs.weblate.org/en/latest/admin/projects.html#monolingual-components

**Comment by Rvanlaak** [comment]
Thanks for pointing me to the monolingual components, wasn't totally clear to me how to archieve this. Will dive into those and make new issues for possible feature requests or discussions.
