### ISSUE TITLE
Word count statistics

### ISSUE THREAD

**Issue by wichert** [nijel/weblate#807]
Translators often use word counts for vary to create estimates for time and costs, or to create invoices when they are done. It would be incredibly nice if Weblate can facilitate that process. I see two aspects to that:

* in addition to number of untranslated messages, also show the number of words for all untranslated messages
* show activity per translator with word counts

**Comment by nijel** [comment]
The statistics are already there: https://hosted.weblate.org/projects/weblate/master/az/

If you want to process them, they are exported in the JSON: https://docs.weblate.org/en/latest/api.html?highlight=statistics#get--exports-stats-%28string-project%29-%28string-component%29-

Only the per translator stats are missing.

**Comment by wichert** [comment]
That shows translated words, not untranslated words. I can get there by using the percentage and a simple calculation, but seeing that directly would be nice.

**Comment by nijel** [comment]
Added in git.

**Comment by nijel** [comment]
Per word reports will be available for admins/owners after #835 is implemented.

**Comment by nijel** [comment]
With #835 completed, I believe there is nothing left here.

**Comment by Frexuz** [comment]
Hi. I'm also trying to get per-user stats since we pay our translators per word. I'm looking at the RSS feed here: https://translate.frexity.com/api/components/flately/web/statistics/ 

But I don't understand it quite.
```
            "last_author": "Brian Law",
            "total_words": 833,
            "translated_words": 833,

            "last_author": "Vivian Yeung",
            "total_words": 833,
            "translated_words": 787,
```

If Brian translated all the available words, there should be no words left (unless you change current translations). Then how can Vivian have 787 translated ones? (She has only done 'Strings needing actions') :)

Also, in #835 you mention **contributor stats in terms of translated units and words in given interval**, but I'm not sure where to find this report and how to give it an interval :) That would be awesome find calculate translated words each month to know how much work has been done/how much to pay.

**Comment by Frexuz** [comment]
Oh, i missed the rss was different language codes 😓 
And thanks for the correct link to the reports, works 👍 <3
