### ISSUE TITLE
add support for language reviewers

### ISSUE THREAD

**Issue by stanislav-brabec** [nijel/weblate#867]
The current Weblate permission system allows to split users to groups with different permissions. But these permissions are language-agnostic. In a real life, different languages can have different requirements.

For example:

Czech translators have a team. Team has a coordinator and reviewer. Only these can add or approve translations directly. Other users can only make suggestions. Reviewers the will approve it or reject.

Hebrew team has no coordinator yet. But they have a team. Approved users can submit directly, others have no permissions. Anybody, who wants to participate, has to ask for permission.

Bengali team is not established yet. Anybody can edit Bengali translations.

**Comment by nijel** [comment]
Indeed some more complex access control is needed, also see #912.

**Comment by matejcik** [comment]
I'm currently poking into this.

My working idea at this moment is to extend Django's permission management system so that permissions are not app-wide, but tied to a particular (sub)project + language combination, with NULL being wildcard.

This would enable us to define language-specific permissions for group "users" to cover the default access ("users" will have full permissions for Bengali, no permissions for global) and create specific groups to cover other purposes ("czech_reviewers" will have full access, "czech_team" can make suggestions? "hebrew_team" has full access)

The downside of this approach is that permissions are always positive, i.e. we can't set "users can suggest" for global and "users can not suggest" for a particular language, unless we list all languages with "can suggest" explicitly and leave out those we want to disable.
Is this a problem? Should I try to figure out something with Deny as well as Allow?

**Comment by nijel** [comment]
I've quickly looked at available solutions and I didn't find some good fit for what we're going to achieve.

As for negative permissions, I'm not sure how this would work for #868, where probably negative permission will be needed to restrict some users for changing particular component. At this point also evaluation order will become important, but I think going first for allow rules ans then for deny one should be safe option...

**Comment by stanislav-brabec** [comment]
Do I understand it that admin will have to maintain listing of all languages that don't have a review team? It does not sound friendly.

And do I understand correctly that there is a problem that allowing negative permissions would need priorities to detect, which rule wins?

What about assigning of negative permissions to languages or sub-projects, not to users:
cs language: Cannot edit translations unless can_edit_cs
SLE13 sub-project: Cannot edit translation unless sle13_admin

**Comment by matejcik** [comment]
attempted current solution:

In phase 1, each "object" (project, subproject, language, combination) gets a list of groups that are allowed to access it.
Only permissions gained from those groups apply to the given object

**Comment by matejcik** [comment]
a big unsolved question is actually what to do when the "objects" overlap.
my current thinking is that there is a strict hierarchy: Language < Project < Subproject
and only restrictions from the highest relevant level apply
So if a project ProjectX excludes everyone but "projectx_team", then "projectx_team" has full rights to all czech translations in ProjectX, even though they are not members of "czech_translators"; and members of "czech_translators" don't get to edit ProjectX unless they're also on "projectx_team".

**Comment by nijel** [comment]
Should be fixed by #963.

**Comment by matejcik** [comment]
I have discovered a flaw in the current implementation. It allows the administrator to restrict access to a certain translation object to a given group, but it doesn't restrict this group's privileges when outside the given translation object.

So if, for example, we want to give czech_translators commit rights for Czech language, we add the respective privilege to the czech_translators group ... but now every Czech translator has commit rights to Czech language, **and also** to every object that isn't restricted by a different group ACL rule.

I don't fully understand what the different privileges do, so i don't know how big a problem this would be in practice. (IIRC also many of the rights are tied to a project and do not respect the group ACL mechanism anyway; that's something that might need to be fixed too)

To solve this, maybe the czech_translators group needs to become "locked down" when first used in a group ACL rule, and that means that privileges gained from this group only apply to the object in question?

**Comment by nijel** [comment]
Indeed it seems to be like that. What I think should be final state is that if there is GroupACL for given group, it would not use it in normal permission model.

I think attached patch would do that, but I don't have time to test it. Assuming you have some GroupACL test setup, it would be great if you could look at it.
[group-perms.patch.txt](https://github.com/nijel/weblate/files/134921/group-perms.patch.txt)

**Comment by matejcik** [comment]
No reason to override `_get_group_permissions`, `get_group_permissions` without underscore should work just as well.

In any case, the problem with this (and the reason why I decided to implement GroupACL inside the `trans` module, as opposed to directly on the `WeblateUserBackend`) is that it makes the backend depend on the `trans` module. It didn't seem to be a good idea at the time, but I don't know, maybe this is OK for you?

As an alternative, I could add the permissions check to the `has_group_perm` method, and make sure that it is used in all cases in weblate.

**Comment by nijel** [comment]
By overriding ``get_group_permissions`` you loose caching on the group permissions, that's why I've chosen to overwrite this one.

As for dependency it's true, but moving the check to the ``has_group_perm`` might be solution, but I don't see way to do it there without reimplementing quite lot of logic hidden behind ``User.has_perm``.

**Comment by nijel** [comment]
For now I've applied patch linked above. If you can provide better solution, patches are welcome :-).
