### ISSUE TITLE
Messages comments should be more prominent

### ISSUE THREAD

**Issue by wichert** [nijel/weblate#933]
It is possible to add comments to a message. This is often used to tell translators how a piece of text is used, what the proper tone of voice is, or various other kinds of information. Those comments are *critical* when making a translation.

With the current UI for weblate message commends are almost hidden: they are shown in a small font in the "Source Information" portlet on the right edge of the screen. This almost guarantees that translators will not see them. I would like to see these comments to be much more prominent. Ideally right at the top in the "Translate" box next to the source text.

**Comment by nijel** [comment]
The comment is shown quite prominently next to the source:

https://hosted.weblate.org/translate/phpmyadmin/master/af/?q=%25B+%25d%2C+%25Y+at+%25I%3A%25M+%25p&search=exact&source=on

But once the unit has context (what is always true for monolingual translations), it is shown there instead. Maybe the priorities should be changed here...

**Comment by wichert** [comment]
Hm, so it is. I think my issue is then that the comment becomes a bit lost if you also have other reference translations. Here is a screenshot from our system:

![image](https://cloud.githubusercontent.com/assets/199657/11142470/c3bd4490-89ed-11e5-9b28-e205608257dc.png)

Change the class for the comment to `comment alert alert-info` makes it much more noticable:

![image](https://cloud.githubusercontent.com/assets/199657/11142513/179bd40a-89ee-11e5-8852-83a46d890ac6.png)

The vertical alignment is a bit off, and using an alert is a bit of a big hammer but in terms of UX our translators seem to find that more convenient.

**Comment by nijel** [comment]
It's always trade off between space it consumes and visibility. The translation page has already troubles to fit into smaller screen and this would make it just worse. I need to think a bit more about how to resolve this...

**Comment by dg0yt** [comment]
I have trouble with the visibility of developer comments, too. What I find most confusing is the fact that there are two places with source comments: 
- the Comments tab below the Translate frame (for online discussion),
- the Comments field in the Source information frame (for upstream source comments).

I wonder if the upstream source comments shouldn't be merged into the online comments (without Delete button). The availability of inline comments is quite visible even if the tab is not selected, as the number is always highlighted.

On the other hand, the kind of comments I add to the source code should really always be displayed next to the source string, because it may provide neccessary context such as the required tense ([example](https://hosted.weblate.org/translate/openorienteering/mapper/fr/?q=Cut+%25n+object%28s%29&search=substring&source=on&type=all&ignored=False)).

I really like the proposal in the second screenshot. Maybe space consumption could be controlled by making the comment collapsible. Display only a single line until uncollapsed.

Finally, in a few cases I accidently used (a part of) the context for entering source comments. This text is displayed next to the source string. This text is displayed in the Translate frame, but doesn't really improve UX for translators ([example](https://hosted.weblate.org/translate/openorienteering/mapper/fr/?q=From+center&search=substring&source=on&type=all&ignored=False)).

**Comment by dg0yt** [comment]
Related to #1060.
